bmonkey_bakend_login:
    pattern: /login
    defaults: { _controller: BmonkeyBackendBundle:Login:login }

bmonkey_login_check:
    pattern: /login_check

bmonkey_logout:
    pattern: /logout

bmonkey_bakend_dashboard:
    path:     /dashboard
    defaults: { _controller: BmonkeyBackendBundle:Default:dashboard }

bmonkey_bakend_prueba:
    path:     /prueba
    defaults: { _controller: BmonkeyBackendBundle:Default:prueba }

